### PR TITLE
(#247) Name param in event tracking to handle both http and https

### LINKED ISSUE #247: Name parameter in event tracking is not accounting for http protocol
### Issue description
*Description of the issue*
Event tracking on every single view/component is sending a name parameter that only handles https protocols. 
`name: canonicalHost.replace('https://', '') + window.location.pathname,` - now this should probably be a regex to remove both http and https.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Look at all components/views that fires events
2. 
3. 

### What's the expected result?
- it should remove both http and https protocol

### What's the actual result?
- it only handles https protocol

### Additional details / screenshot
- Screenshot

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by belaolsonNIH**
- name parameter in event tracking now handles both http and https protocols 
Closes #247

### CODE REVIEW

**Review by seyilonge-nci — APPROVED** [review]

**Review by sarinapadilla — APPROVED** [review]
`react-app-dev` works, so this passes for me!

File: src/views/Terms/TermList.jsx [hunk 1]
```diff
@@ -80,7 +80,7 @@ const TermList = ({ matchType, query, type }) => {
 		const searchParams = {
 			event: 'GlossaryApp:Load:SearchResults',
 			name:
-				canonicalHost.replace('https://', '') +
+				canonicalHost.replace(/https:\/\/|http:\/\//, '') +
```
Comment (KateMashkinaNIH) [inline src/views/Terms/TermList.jsx:83]: there is one more place to update it : GlossaryApp:Load:ExpandResults event

**Review by KateMashkinaNIH — CHANGES_REQUESTED** [review]

**Review by KateMashkinaNIH — APPROVED** [review]

**Review by arcepaul — APPROVED** [review]
