### PR TITLE
(#161)fixed the name parameter for expand and search results

### LINKED ISSUE #161: The name value in pageLoad events for search and expand is wrong
### Issue description
*Description of the issue*
The name parameter is not changing dynamically based on the language of an app
> **ESTIMATE** 20

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot
- Screenshot

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by kate-mashkina**
Closes #161

### CODE REVIEW

File: src/views/Terms/TermList.jsx [hunk 1]
```diff
@@ -31,7 +31,13 @@ const TermList = ({ matchType, query, type }) => {
...
 		{ language, canonicalHost, dictionaryTitle, siteName, basePath },
 	] = useStateValue();
-	const { DefinitionPath, HomePath } = useAppPaths();
+	const {
+		DefinitionPath,
+		HomePath,
+		ExpandPath,
+		ExpandPathSpanish,
+		SearchPath,
+		SearchPathSpanish } = useAppPaths();
```
Comment (seyilonge-nci) [inline src/views/Terms/TermList.jsx:40]: Did you run the linter on this? I would expect that `} = useAppPaths();` would get placed on a new line

Comment (kate-mashkina) [reply src/views/Terms/TermList.jsx:40]: I used the short cut `option + shift + F`

Comment (kate-mashkina) [reply src/views/Terms/TermList.jsx]: moved to a new line
